// Saffron Kitchen design tokens — matches the Tailwind config in your HTML files
export const C = {
  primary: '#8f4e00',
  primaryContainer: '#ff9933',
  onPrimaryContainer: '#693800',
  onPrimary: '#ffffff',
  primaryFixed: '#ffdcc2',
  primaryFixedDim: '#ffb77a',
  secondary: '#b52619',
  secondaryContainer: '#ff5c47',
  onSecondary: '#ffffff',
  surface: '#fcf9f8',
  background: '#fcf9f8',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#f6f3f2',
  surfaceContainer: '#f0eded',
  surfaceContainerHigh: '#eae7e7',
  surfaceContainerHighest: '#e5e2e1',
  surfaceVariant: '#e5e2e1',
  onSurface: '#1c1b1b',
  onSurfaceVariant: '#554336',
  outlineVariant: '#dbc2b0',
  outline: '#887364',
  error: '#ba1a1a',
  errorContainer: '#ffdad6',
};
